name: Deploy prod avtoas

on:
  push:
    branches:
      - prod

env:
  VPS_IP: 46.254.19.97
  VPS_USERNAME: di4basa7
  DIR: /var/www/di4basa7/data/www/prod
  TELEGRAM_TO: 360209578, 1022228978, 663501687

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build assets
        run: |
          npm ci
          npm run prod

      - name: git pull on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            chown -R di4basa7:di4basa7 ${{ env.DIR }}
            cd ${{ env.DIR }}
            git config --global user.email "1@php-cat.com"
            git config --global user.name "Sergey"
            git fetch --all
            git reset --hard origin/prod

      - name: composer + migrate
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ env.DIR }}
            /opt/php80/bin/php ./composer.phar i --no-dev
            /opt/php80/bin/php artisan migrate

      - name: Deploy built assets
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "public/js/app.js,public/js/app.js.LICENSE.txt,public/css/app.css,public/mix-manifest.json"
          target: ${{ env.DIR }}

#      - name: send telega
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ env.TELEGRAM_TO }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: |
#            🍀🍀🍀 обновления заведены, установлены, сайт обновлён
#            👨🏻‍💻 ${{github.actor}} в репозиторий ${{ github.repository }}
#            сделал ${{ github.event_name }}. задание ${{github.job}}.

  sms_start:
    runs-on: ubuntu-latest
    steps:
      - name: sms_vk_start
        run: |
          curl -X POST "https://api.php-cat.com/api/vk/send" \
            -H "Content-Type: application/json" \
            -d '{
              "group_name": "tech",
              "user_id": 5903492,
              "message": "🚀🚀🚀 ${{ github.repository }} Старт деплоя \n 💻 ${{ github.actor }} (${{ github.run_id }}) \n 📝 ${{ github.event.head_commit.message }} "
            }'

  sms_end:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: sms_vk
        run: |
          curl -X POST "https://api.php-cat.com/api/vk/send" \
            -H "Content-Type: application/json" \
            -d '{
              "group_name": "tech",
              "user_id": 5903492,
              "message": "🍀🍀🍀 ${{ github.repository }} Deployment finished \n ‍💻 ${{ github.ref_name }} ++ ${{ github.actor }} (${{ github.run_id }}) "
            }'
        if: success()

      - name: Send Telegram notification (failure)
        uses: appleboy/telegram-action@master
        with:
          to: 360209578, phpcat
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚨🚨🚨 ${{ github.repository }} 👨🏻‍💻 ${{ github.actor }} > ${{ github.run_id }}
            ${{ github.event_name }} > ${{ github.event.head_commit.message }}
            Ошибка деплоя! Проверьте логи.
        if: failure()
