name: test кода на avto-as.ru

env:
  VPS_IP: 46.254.19.97
  VPS_USERNAME: di4basa7
  DIR: www/lara2
  DIR_PROD: www/prod
  GIT_BRANCH: origin/main
  GIT_BRANCH_PROD: origin/prod

on:
  schedule:
    - cron: "37 08 * * *"
  workflow_dispatch:
# inputs:
#   deployment_target:
#     description: Choose target
#     required: true
# default: second_test
# type: 
# options:
#   - тест боевого сайта
#   - тест сайта разработки

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: тест боевого сайта
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${{ env.DIR_PROD }}
            /opt/php74/bin/php artisan test

  sms_start:

    runs-on: ubuntu-latest
    steps:

      - name: send telega
        uses: appleboy/telegram-action@master
        with:
          # to: ${{ secrets.TELEGRAM_TO }}
          # я / Авто-АС / Денис Авто-СА
          to: 360209578, 1022228978, 663501687 
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🐥🐥🐥 старт теста кода avto-as.ru
            (${{ github.run_id }})

  sms_end:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: send telega
        uses: appleboy/telegram-action@master
        with:
          # to: ${{ secrets.TELEGRAM_TO }}
          # я / Авто-АС / Денис Авто-СА
          to: 360209578, 1022228978, 663501687 
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🍀🍀🍀 Тест проведён успешно
            ${{ github.run_id }}
